resources:
 pipelines:
  - pipeline: buildContosoAir # identifier for the resource used in pipeline resource variables
    source: Student1-48230296.ContosoAir # name of the pipeline that produces the artifact
    trigger:
     branches:
      include:
       - master

trigger:
- none

pool:
    name: default

stages:
- stage: deploy
  jobs:
  - job: deployJob
    workspace:
      clean: all
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: '4a60e52a-a655-490b-a030-a91ab9d897af'
        definition: '4'
        buildVersionToDownload: 'latest'
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Azure Connection'
        subscriptionId: '43ebd196-f6ab-4ab6-ba3e-02673e875291'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'rg-lod'
        location: 'Canada Central'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.json'
        csmParametersFile: '$(Pipeline.Workspace)/drop/Templates/azuredeploy.parameters.json'
        overrideParameters: '-p_environment $(web_environment) -p_site_prefix $(web_prefix) -p_site_web_name $(web_site)'
        deploymentMode: 'Incremental'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure Connection'
        appType: 'webApp'
        WebAppName: '$(web_prefix)-$(web_site)-$(web_environment)'
        packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
